const menu = [
  {
    id: 1,
    title: "Idli",
    category: "breakfast",
    price: 20.0,
    img: "./images/item-1.jpeg",
    desc: `Idli Sambar is a hearty, satisfying, comforting and a healthy meal of soft fluffy idlis served with savory, spiced and lightly tangy sambar – a vegetable stew made with lentils and assorted vegetables.`,
  },
  {
    id: 2,
    title: "Chicken Biriyani",
    category: "lunch",
    price: 100.0,
    img: "./images/item-2.jpeg",
    desc: `Chicken Biryani is a delicious savory rice dish that is loaded with spicy marinated chicken, caramelized onions, and flavorful saffron rice. For my Biryani, I simplify the order of operations, while retaining the traditional layered approach to assembling it.`,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 110,
    img: "./images/item-3.jpeg",
    desc: `A milkshake is a sweet drink made by blending milk, ice cream, and flavorings or sweeteners such as butterscotch, caramel sauce, chocolate syrup, fruit syrup, or whole fruit into a thick, sweet, cold mixture. `,
  },
  {
    id: 4,
    title: "Masal Dosa",
    category: "breakfast",
    price: 45.0,
    img: "./images/item-4.jpeg",
    desc: `Masala dosa is a variation of the popular South Indian dosa, which has its origins in Tuluva Mangalorean cuisine of Karnataka. It is made from rice, lentils, potato, fenugreek, ghee and curry leaves, and served with chutneys and sambar`,
  },
  {
    id: 5,
    title: "Meals-Non veg",
    category: "lunch",
    price: 300.0,
    img: "./images/item-5.jpeg",
    desc: `Very few things come close to a sumptuous meal of white rice with sambhar, rasam and curd. Binging on some simple ‘unlimited’ our meals consisting of rice, Add some non-vegetarian options to these meals and you are in foodie heaven!`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 110.0,
    img: "./images/item-6.jpeg",
    desc: `With a bit of cookie crunch, rich chocolate sauce, and creamy texture, it's no wonder that people are so fond of this flavorful Oreo milkshake. Serve with a colorful straw.`,
  },
  {
    id: 7,
    title: "pongal vada",
    category: "breakfast",
    price: 40.0,
    img: "./images/item-7.jpeg",
    desc: `Pongal is a delicious South Indian porridge made with rice and yellow moong lentils. It can be made sweet or savory. Pongal laced with the wonderful flavors of cumin, asafetida, curry leaves, ginger and black pepper`,
  },
  {
    id: 8,
    title: "Veg thali",
    category: "lunch",
    price: 450.0,
    img: "./images/item-8.jpeg",
    desc: `This thali consists of:lentils: dal or sambar. vegetables: a seasonal preparation. chutney: a condiment made with fruit, herbs, spices, and even vegetables . raita: curds usually mixed with some kind of vegetable.`,
  },
  {
    id: 9,
    title: "elaneer payasam",
    category: "shakes",
    price: 50.0,
    img: "./images/item-9.jpeg",
    desc: `Tender coconut with its refreshing water is by itself tasty with all its coolant effect to our body added to it. Here, we are just mixing it with few simple other ingredients to make elaneer payasam.`,
  },
];
export default menu;
